default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'panoptes' %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'panoptes' %>
  pool: <%= ENV.fetch('PG_POOL_SIZE', 5) %>
  prepared_statements: <%= ENV.fetch('PG_PREPARED_STATEMENTS', false) %>
  variables:
    # default 5 minutes for the query exectution (sidekiq uses default, API will set the env param match load balancer)
    statement_timeout: <%= ENV.fetch('PG_STATEMENT_TIMEOUT', 300000) %>

development:
  <<: *default
  database: panoptes_development

staging:
  <<: *default
  database: panoptes

production:
  <<: *default
  database: panoptes

development_standby:
  <<: *default
  database: panoptes_development

test:
  <<: *default
  database: panoptes_test

test_standby:
  <<: *default
  database: panoptes_test
